parameters:
- name: 'initPath'
  type: string
  default: '/etc/init.d/srcds*'

stages:
- stage: 'Restart'
  jobs:
  - job: 'Restart_Server'
    steps:  
    - task: SSH@0
      inputs:
        sshEndpoint: '<ENDPOINT>'
        runOptions: 'commands'
        commands: '${{ parameters.initPath }} restart'
        readyTimeout: '20000'
        interactiveSession: true