parameters:
- name: 'initPath'
  type: string
  default: '/etc/init.d/srcdsBizzymod'

pool:
  name: Local Agents

stages:
- stage: 'Restart'
  jobs:
  - job: 'Restart_Server'
    steps:  
    - task: SSH@0
      inputs:
        sshEndpoint: 'Bizzymod (Dev)'
        runOptions: 'commands'
        commands: 'sudo ${{ parameters.initPath }} restart'
        readyTimeout: '20000'
        interactiveSession: true